### ISSUE TITLE
Simplest query

### ISSUE THREAD

**Issue by m1sta** [PRQL/pyprql#126]
The following code does not work 

````
%load_ext pyprql.magic

%prql duckdb://

!wget https://raw.githubusercontent.com/graphql-compose/graphql-compose-examples/master/examples/northwind/data/csv/products.csv

%%prql
from 'products.csv'
````

and it probably should

**Comment by max-sixty** [comment]
Yes agree, the docs need an update, I'll try and get to that today.

**Comment by max-sixty** [comment]
FYI I didn't get to this today, but this & I'll prioritize this & https://github.com/PRQL/prql/issues/1531, hopefully tomorrow
