### ISSUE TITLE
test with jupysql 0.10dev

### ISSUE THREAD

**Issue by edublancas** [PRQL/pyprql#245]
Hi,

we're going to release JupySQL 0.10 next week, so you might want to check compatibility (you can install from the master branch to do so). We changed the magic setup a bit so we could more easily grab the user's `%config`: https://github.com/ploomber/jupysql/blob/8bcf3adf80eaaf3fe022b8cdb7dc6abd7a503094/src/tests/conftest.py#L90 I think that's the only thing you might need to change but let me know if you encounter any issues!

**Comment by eitsupi** [comment]
Hi @edublancas, thanks for sharing that!

I have been very busy lately and haven't seen this yet, but will check it out when I get some time.
