### ISSUE TITLE
Autoload the saved CSV file from 'to csv' transform ? 

### ISSUE THREAD

**Issue by charlie-sanders** [prql/PyPrql#28]

**Comment by qorrect** [comment]
@rbpatt2019 what do you think about prompting them to load the just saved CSV file ?  Kind of like switching to a new view of the data

**Comment by rbpatt2019** [comment]
Discussed on Discord, but adding thoughts here for completion. I'd lean towards no - a new query can always be used as a table with `table NAME = ( from ... )`, but once it gets loaded into memory, we'd have to restarts the instance to get it back.

**Comment by rbpatt2019** [comment]
Literally as I clicked comment, I realised that the query results could be added as a table to the existing database. Mixed feelings, though. I don't really want every query to add a table to an existing database - but this could be a good option for in-memory sqlite databases. Thoughts @qorrect ? I definitely think adding the connection string to the bar would be super useful.
