### ISSUE TITLE
pyprql no longer runs in Google Colab

### ISSUE THREAD

**Issue by snth** [PRQL/pyprql#381]
Google Colab has changed something and installing pyprql now causes the runtime to crash and it's unable to reconnect.

I think it's actually because of the ipython dependency. Do we need that for anything actually or is that just a convenience? If it's the latter then could we remove it please?

I thought it might be required by jupysql but that does not appear to be the case and the following notebook runs fine on Colab: https://colab.research.google.com/drive/1eOA2FYHqEfZWLYssbUxdIpSL3PFxWVjk?usp=sharing#scrollTo=siVry2OI7HwF

@eitsupi WDYT?

**Comment by max-sixty** [comment]
Do you have a repro? I get this warning but it does seem to run (lightly edited your link with a snippet from the readme):

<img width="444" alt="image" src="https://github.com/PRQL/pyprql/assets/5635139/40146530-24b8-4b52-9ffe-a036f5a3c8b6">

**Comment by eitsupi** [comment]
> I think it's actually because of the ipython dependency. Do we need that for anything actually or is that just a convenience? If it's the latter then could we remove it please?

See #374.
I agree with making it an optional dependency.

**Comment by max-sixty** [comment]
I think this should be fixed by https://github.com/PRQL/pyprql/pull/383

**Comment by max-sixty** [comment]
Indeed, `!pip install git+https://github.com/PRQL/pyprql.git` now works

Thanks for the issue + the repro @snth !
