### ISSUE TITLE
A flag for the console that will store the last transformation as _ , and pass that to the next transformation

### ISSUE THREAD

**Issue by charlie-sanders** [PRQL/pyprql#47]
Example:

from records \<enter\>
_ = (all records)
filter genre = 'pop' \<enter\>
_ = ( pop records )
filter year >= 2000 \<enter\>
_ = (pop records post 2000 )
to csv 'mostly_rhianna.csv' \<enter\>
\# saves results to mostly_rhianna.csv

**Comment by max-sixty** [comment]
This sort of thing would be really cool. 

More generally being able to inspect the intermediate results — particularly on datasets which aren't so large — would be great.

**Comment by charlie-sanders** [comment]
Wonder if we can shove a pageable preview table in the UI somewhere.  Maybe we split the screen, make the top 3 lines long for prql input the bottom a rich.table() that gets updated on keystroke?!  Maybe on enter.

**Comment by max-sixty** [comment]
Closing as TUI
