### ISSUE TITLE
Several minor issues

### ISSUE THREAD

**Issue by swuecho** [prql/PyPrql#60]
1. connection take several seconds.
2. result is not readable for table with many columns.
![image](https://user-images.githubusercontent.com/666683/176356097-db8ef9be-0ae9-4556-8b2a-0f282118cf3b.png)

the result of raw psql is not readable too, but in psql '\x' can be configed and the display is readable
3. if my input is not valid, PRQL will exit. I think it should not exit because of a query.

![image](https://user-images.githubusercontent.com/666683/176356645-ac9bab94-dacc-4d37-aa7d-73a6ce0d1ba2.png)

And thanks for make PRQL available as a repl.  I might fix the issues 2 if add a config option is an acceptable approach.

**Comment by swuecho** [comment]
ideally, all my input history are saved in a .sqlite or  text files.

**Comment by charlie-sanders** [comment]
Thanks for the report, I agree on 2 & 3 I'll open an issue for it.  1 is straight from SQLAlchemy so I doubt there is much we can do there.
