### ISSUE TITLE
Rough edges when reading from stdin

### ISSUE THREAD

**Issue by richb-hanover** [PRQL/pyprql#74]
When using PyPrql  to read a set of `prql` commands from a file, the user experience is a little rough. Or maybe my intuition about how the program should work is faulty (and I am really asking for documentation...) 

Here is a sample file and the resulting output. Invoke with: `pyprql 'sqlite:///chinook.sqlite' < pq4.prql` 

```
# This file - pq4.prql - is for testing PyPrql
# Ensure the chinook database is in the same directory.
# (https://github.com/lerocha/chinook-database)
# Invoke with pyprql 'sqlite:///chinook.sqlite' < pq4.prql

from albums
select title
take 20
;

```
Here are my observations about the process. Refer to the output (below):

1. The final blank line in the _input_ file appears to be mandatory. If that blank line is missing, the SQL command won't execute.
1. There's a warning about stdin not being a terminal. Is this necessary?
2. There's a warning about an exceptions when handling the comments (leading up to "... SyntaxError('No pipelines?'))
3. The PRQL parsed from the input file appears to be correct, as is the SQL output
4. The displayed output (from the SQL query) also seems to be correct
5. After outputting the result table, PyPrql remains at a `PRQL>` prompt. I had expected that PyPrql would terminate after it read all the lines of the input file.
6. There's also a cursor-position-request warning as well.
7. It doesn't show in the copy-pasted terminal session, but there are some VT100-ish cursor positioning codes displayed in the terminal 
10. I had to hit Ctl-C to abort from PyPrql entirely - otherwise, there are VT100 codes left in terminal.
11. I also tried typing the commands into the command line (not reading from a file). They seemed to work as expected; typing `exit`ended the program cleanly. Note that typing comments at the `PRQL>` prompt caused a "no pipelines" error.

```
√ pqtest % pyprql 'sqlite:///chinook.sqlite' < pq4.prql
Connecting to sqlite:///chinook.sqlite
Warning: Input is not a terminal (fd=0).
PRQL> ^[PRQL> # This file - pq4.prql - is for testing PyPrql
....># Ensure the chinook database is in the same directory.
....># (https://github.com/lerocha/chinook-database)
....># Invoke with pyprql 'sqlite:///chinook.sqlite' < pq4.prql
....>
PRQL:	# This file - pq4.prql - is for testing PyPrql|# Ensure the chinook database is in the same directory.|# (https://github.com/lerocha/chinook-database)|# Invoke with pyprql 'sqlite:///chinook.sqlite' < pq4.prql

Exception when handling the input: No pipelines?,SyntaxError('No pipelines?')
Continuing...
PRQL> from albums
....>select title
....>take 20
....>;
PRQL:	from albums|select title|take 20

SQL:
	SELECT
  title
FROM
  albums
LIMIT
  20

Results:
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ title                                    ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ title                                    │
│ For Those About To Rock We Salute You    │
│ Balls to the Wall                        │
│ Restless and Wild                        │
│ Let There Be Rock                        │
│ Big Ones                                 │
│ Jagged Little Pill                       │
│ Facelift                                 │
│ Warner 25 Anos                           │
│ Plays Metallica By Four Cellos           │
│ Audioslave                               │
│ Out Of Exile                             │
│ BackBeat Soundtrack                      │
│ The Best Of Billy Cobham                 │
│ Alcohol Fueled Brewtality Live! [Disc 1] │
│ Alcohol Fueled Brewtality Live! [Disc 2] │
│ Black Sabbath                            │
│ Black Sabbath Vol. 4 (Remaster)          │
│ Body Count                               │
│ Chemical Wedding                         │
└──────────────────────────────────────────┘
PRQL> ^[WARNING: your terminal doesn't support cursor position requests (CPR).
PRQL>


```

**Comment by max-sixty** [comment]
Closing as TUI
